// <auto-generated />
namespace ProjectManagerApp2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class taskChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taskChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201907181621409_taskChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
